version: '3.8'

services:
    java-app:
        image: java-app:latest
        depends_on:
            postgresql:
                condition: service_healthy
        ports:
            - "8080:8080"
        volumes:
            - ./config:/app/config
            - ./logs:/app/logs
    postgresql:
        image: postgres:latest
        environment:
            POSTGRES_USER: user 
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        ports:
            - "5432:5432"
        volumes:
            - ./db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d db"]
            interval: 5s
            retries: 5
